---
- hosts: aws
  gather_facts: False
  tasks:
    - name: Install python
      become: yes
      become_method: sudo
      raw: 'sudo apt-get update && sudo apt-get -y install python3'

    - name: Install python2
      become: yes
      become_method: sudo
      raw: 'sudo apt-get update && sudo apt-get -y install python'

    - name: Install git and cmake
      become: yes
      become_method: sudo
      raw: 'sudo apt-get update && sudo apt-get -y install git-core && sudo apt-get -y install cmake && sudo apt-get -y install rsync'

    - name: Clean santander directory
      file:
        state: absent
        path: ~/santander-transaction

    - name: Create santander directory
      file:
        state: directory
        path: ~/santander-transaction


- hosts: aws
  gather_facts: False
  roles:
    - role: santander_lib
      message: copy code to remote machine

- hosts: aws
  gather_facts: False
  tasks:
    - name: Install pip3
      become: yes
      become_method: sudo
      raw: 'sudo apt-get update && sudo apt-get -y install python3-pip && pip3 install --upgrade pip'

    - name: Install requirements.txt
      raw: 'chmod +x ~/santander-transaction/prediction_lib/requirements.txt && sudo pip3 install -r ~/santander-transaction/prediction_lib/requirements.txt'

- hosts: aws
  gather_facts: False
  roles:
    - role: build_xgboost
      message: build xgboost with support for multithreading

- hosts: aws
  tasks:
    - name: Download file from kaggle
      shell:
        cmd: "cd ~/santander-transaction && kaggle competitions download -c santander-customer-transaction-prediction"