---
- hosts: 192.168.1.13
  connection: local
  gather_facts: False
  tasks:
    - name: Install python
      become: yes
      become_method: sudo
      raw: 'sudo apt-get update && sudo apt-get -y install python3'

    - name: Install git and cmake
      become: yes
      become_method: sudo
      raw: 'sudo apt-get update && sudo apt-get -y install git-core && sudo apt-get -y install cmake'

    - name: Create santander directory
      shell:
        cmd: 'rm -rf ~/santander-transaction && mkdir ~/santander-transaction'


- hosts: 192.168.1.13
  connection: local
  gather_facts: False
  roles:
    - role: santander_lib
      message: copy code to remote machine

- hosts: 192.168.1.13
  gather_facts: False
  tasks:
    - name: Install requirements.txt
      become: yes
      become_method: sudo
      raw: 'chmod +x ~/santander-transaction/prediction_lib/requirements.txt && pip3 install -r ~/santander-transaction/prediction_lib/requirements.txt'

- hosts: 192.168.1.13
  gather_facts: False
  roles:
    - role: build_xgboost
      message: build xgboost with support for multithreading

- hosts: 192.168.1.13
  tasks:
    - name: Download file from kaggle
      shell: |
        cd ~/santander-transaction
        kaggle competitions download -c santander-customer-transaction-prediction