---
- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  roles:
    - role: test_role
      message: 'this is a test role. it does nothing'

- hosts: 127.0.0.1
  connection: local
  roles:
    - role: create_directory
      message: 'create temp-123 directory'