---
# tasks file for build_xgboost
- name: Build xgboost
  become: yes
  become_method: sudo
  shell:
    cmd: "cd ~/santander-transaction
    git clone --recursive https://github.com/dmlc/xgboost
    cd xgboost
    mkdir build
    cd build
    cmake ..
    make -j4"
